name: Fetch Ratings from Sanity

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # allow manual trigger

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Fetch ratings from Sanity
        run: node scripts/fetchSanityRatings.js
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ratings.json
          git diff --quiet && echo "No changes" || (git commit -m "Update ratings.json" && git push)
