name: Fetch Ratings from Sanity

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  fetch-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Fetch ratings from Sanity
        run: node scripts/fetchSanityRatings.js
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_API_TOKEN: ${{ secrets.SANITY_API_TOKEN }}

      - name: Fetch coordinates for ratings
        run: node scripts/fetchGeo.js

      - name: Commit if changed or new
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add src/ratings.json src/coords.json

          if git diff --cached --quiet; then
            if git ls-files --others --exclude-standard | grep -q '^src/ratings.json\|^src/coords.json$'; then
              echo "🟡 Untracked file(s) found, committing."
              git commit -m "Add initial ratings.json and coords.json"
              git push
              echo "should_deploy=true" >> "$GITHUB_OUTPUT"
            else
              echo "🟢 No changes to commit."
              echo "should_deploy=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "🟠 Changes found in tracked file(s), committing."
            git commit -m "Update ratings.json and/or coords.json"
            git push
            echo "should_deploy=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Build
        if: steps.commit.outputs.should_deploy == 'true'
        run: npm run build

      - name: Deploy
        if: steps.commit.outputs.should_deploy == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
